document.write("<section class=\"contact section-padding\" id=\"section_5\">");
document.write("	<div class=\"container\">");
document.write("		<div class=\"row\">");
document.write("			<div class=\"col-lg-3\" style=\"display:flex;justify-content:center;\">");
document.write("				<img src=\"..\/..\/images\/icons\/logo_land.png\" class=\"brand-image img-fluid\" alt=\"\">");
document.write("			<\/div>");
document.write("");
document.write("			<div class=\"col-lg-3 col-md-6 col-12 ps-lg-0\">");
document.write("				<div class=\"contact-info flex-column\">");
document.write("					<h6>社交平台<\/h6>");
document.write("					<p>Social Platform<\/p>");
document.write("					<br\/>");
document.write("					<hr style=\"width:40px;\"\/>");
document.write("					<br\/>");
document.write("");
document.write("					<ul class=\"social-icon\">");
document.write("						<li class=\"social-icon-item wechat-icon\">");
document.write("							<a href=\"#section_5\">");
document.write("								<img src=\"..\/..\/images\/index\/icon_wechat.png\"");
document.write("								     alt=\"wechat-icon\"");
document.write("								     onmouseover=\"this.src='..\/..\/images\/index\/icon_wechat_hover.png'\"");
document.write("								     onmouseout=\"this.src='..\/..\/images\/index\/icon_wechat.png'\"\/>");
document.write("							<\/a>");
document.write("						<\/li>");
document.write("");
document.write("						<li class=\"social-icon-item tiktok-icon\">");
document.write("							<a href=\"#section_5\">");
document.write("								<img src=\"..\/..\/images\/index\/icon_tiktok.png\"");
document.write("								     alt=\"tiktok-icon\"");
document.write("								     onmouseover=\"this.src='..\/..\/images\/index\/icon_tiktok_hover.png'\"");
document.write("								     onmouseout=\"this.src='..\/..\/images\/index\/icon_tiktok.png'\"\/>");
document.write("							<\/a>");
document.write("						<\/li>");
document.write("");
document.write("						<li class=\"social-icon-item weibo-icon\">");
document.write("							<a href=\"#section_5\">");
document.write("								<img src=\"..\/..\/images\/index\/icon_weibo.png\"");
document.write("								     alt=\"weibo-icon\"");
document.write("								     onmouseover=\"this.src='..\/..\/images\/index\/icon_weibo_hover.png'\"");
document.write("								     onmouseout=\"this.src='..\/..\/images\/index\/icon_weibo.png'\"\/>");
document.write("							<\/a>");
document.write("						<\/li>");
document.write("					<\/ul>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("");
document.write("			<div class=\"col-lg-3 col-md-6 col-12 ps-lg-0\">");
document.write("				<div class=\"contact-info flex-column\">");
document.write("					<h6>联系我们<\/h6>");
document.write("					<p>Contact Us<\/p>");
document.write("					<br\/>");
document.write("					<hr style=\"width:40px;\"\/>");
document.write("					<br\/>");
document.write("");
document.write("					<p>");
document.write("						Tel：");
document.write("						<a href=\"tel: 138-2219-5955\">");
document.write("							138-2219-5955");
document.write("						<\/a>");
document.write("					<\/p>");
document.write("");
document.write("					<p>");
document.write("						E-mail：");
document.write("						<a href=\"mailto:3358137216@qq.com\">");
document.write("							3358137216@qq.com");
document.write("						<\/a>");
document.write("					<\/p>");
document.write("");
document.write("					<p>");
document.write("						Add：广州市天河区灵山东路4号十一楼1101单元283号房");
document.write("					<\/p>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("");
document.write("			<div class=\"col-lg-3 col-md-6 col-12 ps-lg-0\">");
document.write("				<div class=\"contact-info flex-column\">");
document.write("					<h6>运营团队<\/h6>");
document.write("					<p>Operation Team<\/p>");
document.write("					<br\/>");
document.write("					<hr style=\"width:40px;\"\/>");
document.write("					<br\/>");
document.write("");
document.write("					<ul class=\"footer-menu\">");
document.write("						<li class=\"footer-menu-item\"><a href=\"#section_5\" class=\"footer-menu-link\">广州研发中心<\/a><\/li>");
document.write("");
document.write("						<li class=\"footer-menu-item\"><a href=\"#section_5\" class=\"footer-menu-link\">上海销售中心<\/a><\/li>");
document.write("");
document.write("						<li class=\"footer-menu-item\"><a href=\"#section_5\" class=\"footer-menu-link\">成都办事处<\/a><\/li>");
document.write("");
document.write("						<li class=\"footer-menu-item\"><a href=\"#section_5\" class=\"footer-menu-link\">杭州生产中心<\/a><\/li>");
document.write("					<\/ul>");
document.write("					<img src=\"..\/..\/images\/icons\/recs.png\" class=\"brand-image img-fluid\" style=\"height: 60px\" alt=\"\">");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/section>");
document.write("<footer class=\"site-footer\">");
document.write("	<div class=\"container\">");
document.write("		<div class=\"row\">");
document.write("");
document.write("			<div class=\"col-lg-12 col-12\">");
document.write("				<div class=\"copyright-text-wrap\">");
document.write("					<p class=\"mb-0\">");
document.write("						<span class=\"copyright-text\">Copyright © <Text");
document.write("								id=\"copyRightYear\">2036<\/Text> <a href=\"#\">Colorfulmed<\/a> Company. All rights reserved.<\/span>");
document.write("						<a rel=\"sponsored\" href=\"#\" target=\"_blank\">五色喜公司 版权所有<\/a>");
document.write("					<\/p>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/footer>");
document.write("<script src=\"..\/..\/js\/jquery.min.js\"><\/script>");
document.write("<script src=\"..\/..\/js\/bootstrap.min.js\"><\/script>");
document.write("<script src=\"..\/..\/js\/jquery.sticky.js\"><\/script>");
document.write("<script src=\"..\/..\/js\/click-scroll.js\"><\/script>");
document.write("<script src=\"..\/..\/js\/jquery.magnific-popup.min.js\"><\/script>");
document.write("<script src=\"..\/..\/js\/magnific-popup-options.js\"><\/script>");
document.write("<script src=\"..\/..\/js\/custom.js\"><\/script>");
document.write("<script src=\"..\/..\/js\/copyright-year.js\"><\/script>");
