document.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.write("");
document.write("        <meta name=\"description\" content=\"\">");
document.write("        <meta name=\"author\" content=\"TemplateMo\">");
document.write("");
document.write("        <title>Colorfulmed 五色喜<\/title>");
document.write("");
document.write("        <!-- CSS FILES -->");
document.write("        <link rel=\"preconnect\" href=\"https:\/\/fonts.googleapis.com\">");
document.write("        ");
document.write("        <link rel=\"preconnect\" href=\"https:\/\/fonts.gstatic.com\" crossorigin>");
document.write("        ");
document.write("        <link href=\"https:\/\/fonts.googleapis.com\/css2?family=DM+Sans:wght@400;500;700&display=swap\" rel=\"stylesheet\">");
document.write("");
document.write("        <link href=\"..\/..\/css\/bootstrap.min.css\" rel=\"stylesheet\">");
document.write("");
document.write("        <link href=\"..\/..\/css\/bootstrap-icons.css\" rel=\"stylesheet\">");
document.write("");
document.write("        <link href=\"..\/..\/css\/magnific-popup.css\" rel=\"stylesheet\">");
document.write("");
document.write("        <link href=\"..\/..\/css\/templatemo-first-portfolio-style.css\" rel=\"stylesheet\">");
document.write("");
document.write("        <link rel=\"shortcut icon\" href=\"..\/..\/images\/icons\/icon_colorfulmed.png\" type=\"image\/x-icon\">");
